mysqladmin -u ${DBROOT_USER} password ${DBROOT_PASS}
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "create database mybb;"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "CREATE USER '${MYBB_DATABASE_USER}'@'%' IDENTIFIED BY '${MYBB_DATABASE_PASS}';"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "GRANT ALL PRIVILEGES ON mybb.* TO '${MYBB_DATABASE_USER}'@'%' IDENTIFIED BY '${MYBB_DATABASE_PASS}';"

#now lets initialise the database
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} mybb < mybb.sql
