#!/bin/bash

MYBB_EXTERNAL_DNS=$1
MYBB_ADMINEMAIL=$2
MYBB_DATABASE_NAME=$3
MYBB_DATABASE_USER=$4
MYBB_DATABASE_PASS=$5
MYBB_DATABASE_HOST=$6
MYBB_DATABASE_PORT=$7
DBROOT_USER=$8
DBROOT_PASS=$9

mysqladmin -u ${DBROOT_USER} password ${DBROOT_PASS}
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "create database mybb;"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "CREATE USER '${MYBB_DATABASE_USER}'@'%' IDENTIFIED BY '${MYBB_DATABASE_PASS}';"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} -e "GRANT ALL PRIVILEGES ON mybb.* TO '${MYBB_DATABASE_USER}'@'%' IDENTIFIED BY '${MYBB_DATABASE_PASS}';"

#now lets initialise the database
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h ${MYBB_DATABASE_HOST} -P ${MYBB_DATABASE_PORT} mybb < mybb.sql
