mysqladmin -u ${DBROOT_USER} -p${DBROOT_PASS}
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h $MYBB_DATABASE_HOST -P $MYBB_DATABASEPORT -e "create database mybb;"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h $MYBB_DATABASE_HOST -P $MYBB_DATABASEPORT -e "CREATE USER '${MYBB_DATABASE_USER}'@'%' IDENTIFIED BY '${MYBB_DATABASE_PASS}';"
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h $MYBB_DATABASE_HOST -P $MYBB_DATABASEPORT -e "GRANT ALL PRIVILEGES ON mybb.* TO '${MYBB_DBUSER}'@'%' IDENTIFIED BY '${MYBB_DBPASS}';"

#now lets initialise the database
mysql -u ${DBROOT_USER} -p${DBROOT_PASS} -h $MYBB_DATABASE_HOST -P $MYBB_DATABASEPORT mybb < mybb.sql
